export const GLOBALTYPES = {
  AUTH: "AUTH",
  LOGOUT: "LOGOUT",
  RE_AUTH: "RE_AUTH",

  CURRENTCONVERSATION: "CURRENTCONVERSATION",

  GETALLYOURFRIENDS: "GETALLYOURFRIENDS",
  START_LOADING: "START_LOADING",
  END_LOADING: "END_LOADING",

  ADDMESSAGE: "ADDMESSAGE",
  GETALLMESSAGE: "GETALLMESSAGE",

  ADDGROUPMESSAGE: "ADDGROUPMESSAGE",
  GETALLGROUPMESSAGE: "GETALLGROUPMESSAGE",

  GETALLGROUPWITHUSER: "GETALLGROUPWITHUSER",

  GETUNSEENMESSAGES: "GETUNSEENMESSAGES",

  GETALLCONVERSATION: "GETALLCONVERSATION",
  // modal
  
  SHOW_OTP_MODAL: "SHOW_OTP_MODAL",
  SHOW_ADDFRIEND_MODAL:"SHOW_ADDFRIEND_MODAL",
  SHOW_ADDGROUP_MODAL:"SHOW_ADDGROUP_MODAL",
  SHOW_CHANGE_GROUP_NAME_MODAL:"SHOW_CHANGE_GROUP_NAME_MODAL",
  SHOW_FORM_SETTING_MODAL:"SHOW_FORM_SETTING_MODAL",
  SHOW_FORM_CHANGE_PASSWORD_MODAL:"SHOW_FORM_CHANGE_PASSWORD_MODAL",
  SHOW_DELETE_MEMBER_GROUP_MODAL:"SHOW_DELETE_MEMBER_GROUP_MODAL",
  HIDE_MODAL:"HIDE_MODAL",
  SHOW_ADD_FRIEND_TO_GROUP_MODAL:"SHOW_ADD_FRIEND_TO_GROUP_MODAL",
  REMOVE_USER_SUCCESS:"REMOVE_USER_SUCCESS",
  GET_USER_SUCCESS:"GET_USER_SUCCESS",
  POST_CONVERSATION:"POST_CONVERSATION",
  DELETEMESSAGE:"DELETEMESSAGE",
  SHOW_ADD_FRIEND_TO_GROUP_MODAL:"SHOW_ADD_FRIEND_TO_GROUP_MODAL",
  ADDSOCKET:"ADDSOCKET",
  UPDATE_COUNT_WAITING_MESSAGE:"UPDATE_COUNT_WAITING_MESSAGE",
  REMOVE_COUNT_WAITING_MESSAGE:"REMOVE_COUNT_WAITING_MESSAGE",
  UPDATE_LAST_MSG_CONVERSATION:"UPDATE_LAST_MSG_CONVERSATION",
  SHOW_OTP_MODAL:"SHOW_OTP_MODAL"
};
